### ISSUE TITLE
ImportError: cannot import name 'CustomLog'

### ISSUE THREAD

**Issue by danieleb0101** [Yelp/detect-secrets-server#2]
When using the latest version of detect-secrets-server I have the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/detect-secrets-server", line 7, in <module>
    from detect_secrets_server.__main__ import main
  File "/usr/local/lib/python3.6/site-packages/detect_secrets_server/__main__.py", line 9, in <module>
    from detect_secrets.core.log import CustomLog
ImportError: cannot import name 'CustomLog'
```
The class `CustomLog` has been deleted from `detect_secrets.core.log` with this commit https://github.com/Yelp/detect-secrets/commit/07af81625800cbf34af0a0b247182c2678c01b93#diff-803075a3f7995bb307c8b7b8afffb403 .
However, detect-secrets-server still relies on `CustomLog` from `detect_secrets.core.log`.

detect-secrets-server should be updated accordingly to the changes that have been done in detect-secrets

**Comment by KevinHock** [comment]
Thanks so much for the PR, I will leave this issue open until we release a new version 👍  As a reminder to add it to the changelog

**Comment by domanchi** [comment]
Closing this issue, as this no longer exists in the new version `0.2.0`.
