### ISSUE TITLE
Manual scan of a directory

### ISSUE THREAD

**Issue by c0debreaker** [Yelp/detect-secrets-server#33]
Does detect-secrets-server come with a tool which we can execute manually to search for secrets in a given directory?

**Comment by KevinHock** [comment]
https://github.com/Yelp/detect-secrets/blob/master/README.md#command-line Might help you 👍

**Comment by c0debreaker** [comment]
Thank you! That's what I found yesterday and I tried it and it works. However, I created a new ticket in that repo.
