### ISSUE TITLE
ImportError: cannot import name SensitivityValues

### ISSUE THREAD

**Issue by dcepler** [Yelp/detect-secrets-server#4]
When installing latest version of **detect-secrets-server** using:

```
git clone https://github.com/Yelp/detect-secrets-server.git /usr/share/detect-secrets-server
pip install /usr/share/detect-secrets-server
```

I have the following error when trying to execute **detect-secrets-server**:
```
Traceback (most recent call last):
  File "/usr/local/bin/detect-secrets-server", line 7, in <module>
    from detect_secrets_server.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/detect_secrets_server/__main__.py", line 9, in <module>
    from detect_secrets.plugins import SensitivityValues
ImportError: cannot import name SensitivityValues
```

The class `SensitivityValues` has been deleted from **detect-secrets** as noted in this PR https://github.com/Yelp/detect-secrets/pull/44. It references that **detect-secrets-server** should be pinned to specific version but the [README.md](https://github.com/Yelp/detect-secrets-server/blob/master/README.md) does not say which version.

I was able to install using pip with the following pinned version
```
pip install detect-secrets==0.8.8
pip install detect-secrets-server
```

Either [README.md](https://github.com/Yelp/detect-secrets-server/blob/master/README.md)  needs to be updated or the **detect-secrets-server** code needs to be updated accordingly.

**Comment by KevinHock** [comment]
Sorry about that. Thank you more making this @dcepler 👍 

I have added at the top of the [`README.md`](https://github.com/Yelp/detect-secrets-server/blob/master/README.md) that 
"It currently is only compatible with [version `0.8.8`](https://github.com/Yelp/detect-secrets/blob/master/CHANGELOG.md#090) of [`detect-secrets`](https://github.com/Yelp/detect-secrets)." It is on our backlog to make the open-source version of the server compatible with the latest `detect-secrets` but hopefully this will due in the meantime.

**Comment by domanchi** [comment]
Closing this issue, as this issue no longer exists with the new version of detect-secrets-server (`0.2.0`).
