### ISSUE TITLE
the module is not catching password in xml <password> format

### ISSUE THREAD

**Issue by prashpb** [Yelp/detect-secrets-server#40]
the module is not catching the password in xml <  password  > format in settings.xml file

 < password >abcdefgh</ password >

**Comment by prashpb** [comment]
@domanchi  @KevinHock 
we have few repo's which has settings.xml files and the scan is unable to identify the password in it
which is in format < password  >
Could you please check .

**Comment by OiCMudkips** [comment]
Hi @prashpb this sounds like an issue with the core secret detection engine which is https://github.com/Yelp/detect-secrets, I'm going to close this issue in favour of Yelp/detect-secrets#270.
