### ISSUE TITLE
fails on not finding the email address after scan

### ISSUE THREAD

**Issue by prashpb** [Yelp/detect-secrets-server#41]
The scan fails when the secrets are detected and the email id is not found for the user.
The situation is, the user is no more using the bitbucket and does not have access to bitbucket but once he was having access and pushed code to repository.
Now when the scan is run, and the code fails to fetch the email address and fails, breaks the code.
The Bitbucket UI still shows the user name. 
Instead of error, can this add a empty user details or the name?

File "/usr/local/lib/python3.6/site-packages/detect_secrets_server/__main__.py", line 39, in main
    return actions.scan_repo(args)
  File "/usr/local/lib/python3.6/site-packages/detect_secrets_server/actions/scan.py", line 35, in scan_repo
    _alert_on_secrets_found(repo, secrets.json(), args.output_hook)
  File "/usr/local/lib/python3.6/site-packages/detect_secrets_server/actions/scan.py", line 67, in _alert_on_secrets_found
    _set_authors_for_found_secrets(repo, secrets)
  File "/usr/local/lib/python3.6/site-packages/detect_secrets_server/actions/scan.py", line 86, in _set_authors_for_found_secrets
    _extract_user_from_git_blame_info(blame_info)
  File "/usr/local/lib/python3.6/site-packages/detect_secrets_server/actions/scan.py", line 102, in _extract_user_from_git_blame_info
    **index_of_at_symbol = email.index('@')
ValueError: substring not found**

**Comment by prashpb** [comment]
@domanchi  @KevinHock @OiCMudkips
Could you please take a look.

**Comment by domanchi** [comment]
Hi @prashpb,

I don't understand your issue. It looks like that stack trace has an issue with parsing the email from the `git blame` command run ([source](https://github.com/Yelp/detect-secrets-server/blob/e9f60d683d816d02d740f25fa1799a2a755c9cb3/detect_secrets_server/storage/core/git.py#L138-L147)).

For example:

```
$ git blame detect_secrets_server/actions/scan.py --show-email -L 92,92
505e7910 (<khock@yelp.com> 2019-03-14 16:44:10 -0700 92) def _extract_user_from_git_blame_info(info):
```

My reckoning is that this is the email that the user self-identifies during commit time:

```
$ git config user.email
aaronloo@yelp.com
```

So I'm not sure why this would change when the user's access is changed on Bitbucket. I'd recommend you to start debugging this issue by determining whether the email shows up in the `git blame`, and if it doesn't, find out why.

**Comment by prashpb** [comment]
Thanks for the info. Looks like some users have stored the emails id same same user id and hence the code is failing when it is not finding the @ in the email id field.
