### ISSUE TITLE
compatibility with detect-secrets > 0.8.8

### ISSUE THREAD

**Issue by sdemura** [Yelp/detect-secrets-server#5]
When will this be addressed?

Why are new versions of detect-secrets not compatible with detect-secrets-server?

**Comment by domanchi** [comment]
Hi @sdemura,

Thanks for your patience. The new version `0.2.0` is a re-architecture of the original detect-secret-server, and intends to be compatible with all future versions of `detect-secrets.

This will be released soon! As such, I'm closing this issue.
