### ISSUE TITLE
looking for how many #pragma are used to avoid the scan

### ISSUE THREAD

**Issue by prashpb** [Yelp/detect-secrets-server#57]
@domanchi @KevinHock @OiCMudkips
Hi,
Its more of a question and it would be great if you could help me.
I am looking for generating report on how many files, repo have used pragma comment to avoid getting caught in scan. is there a function in detect-secrets-server which scans whole repo and not just the diff between commits ? or any idea how can I do it for Bitbucket server by scanning whole repo?

**Comment by domanchi** [comment]
Hi @prashpb,

Does `git grep 'whitelist secret'` suffice? We currently do not have a functionality that generates a report of whitelisted secrets, but pull requests are welcome!

To answer your second question, remember that `detect-secrets-server` is just an add-on to the core functionality of `detect-secrets`. That secret scanning engine allows you to scan the whole repo, so hopefully you'll be able to cobble together a solution that fits what you are looking for.

**Comment by KevinHock** [comment]
*(allow|white)list would be the regex I think https://github.com/Yelp/detect-secrets/blob/master/detect_secrets/plugins/common/constants.py#L8

**Comment by prashpb** [comment]
Thank you. I will look into it.
Can we write our own plug-in and use it along with other plug-in which are inbuilt?
