### ISSUE TITLE
Is there a way to scan entire commit history for secrets?

### ISSUE THREAD

**Issue by chriswalz** [Yelp/detect-secrets-server#61]
I know generally speaking it's better to use the preventative methodology, but sometimes you need to scan the entire commit history. 

Is this possible right now?

**Comment by KevinHock** [comment]
Not right right, detect-secrets package doesn’t do that. 

One could make a package that calls detect-secrets to do this, if you wanted to. Using the same function that detect-secrets-server code uses. 

First by Copy/paste/cleanup Or rewrite the truffleHog Code that does this.

**Comment by chriswalz** [comment]
Thanks for the quick response. I'll play around with it
