### ISSUE TITLE
Add ability to scan repo HEAD

### ISSUE THREAD

**Issue by domanchi** [Yelp/detect-secrets-server#9]
### Context

When writing/configuring new plugins, it is very helpful to test them on a known sample set to configure sensitivity. One way of doing this is by running them on a collection of repositories.

Since `detect-secrets-server` already tracks these repositories, why not modify it so that it is able to scan the repository HEAD as well? Currently, it only checks the diff between the last saved commit, and the current HEAD, but it shouldn't be too hard to configure it to only scan the HEAD.

https://github.com/Yelp/detect-secrets-server/blob/1b46e191d6bd67b57bcf87971a62868dfb3e4e32/detect_secrets_server/repos/base_tracked_repo.py#L131-L136

### Proposed Fix

Add a `--head` flag to the scan options to allow the above described behavior. This should probably also imply `--dry-run`, because there's no relevant state you can save if you're only scanning the HEAD.

**Comment by kramer65** [comment]
I can't stress enough how important this one would be for us in clarity. Because at this point, running `detect-secrets scan .` has different output than `detect-secrets-server scan . --local` (for which I've opened [this issue](https://github.com/Yelp/detect-secrets-server/issues/37))

**Comment by prashpb** [comment]
Even we are looking for the same. It will be really helpful if it can scan the repo head.

**Comment by prashpb** [comment]
@domanchi If possible, could you please comment on the plan if you guys are considering the repo head scan from servers.

**Comment by KevinHock** [comment]
Hi @prashpb, this isn't really a feature that Yelp needs, unfortunately. With that said, I'm happy to review any PRs.

**Comment by KevinHock** [comment]
It turns out Yelp did (eventually) need this feature 😁 We will be pushing a new version with this feature by the end-of-the-week probably. (PR was merged earlier today.)

**Comment by joeyscl** [comment]
🎉
